[package]
name = "rins_markdown_parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Simple markdown parser written on Rust"

[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
