[package]
name = "rins_markdown_parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Simple markdown parser written on Rust"

[dependencies]
anyhow = "1.0.93"
clap = "4.5.21"
html-escape = "0.2.13"
pest = "2.7.14"
pest_derive = "2.7.14"
thiserror = "2.0.3"
